spring.application.name=TicClubDataSystem

# Server Port
server.port=8080

# Database Settings (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/tic_club_db
spring.datasource.username=postgres
spring.datasource.password=Alpit@PTSQL2603
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson Configuration
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false

# Mail Settings (Required for JavaMailSender Bean)
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=dummy
spring.mail.password=dummy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

